ALTER TABLE features
ADD COLUMN IF NOT EXISTS created_by VARCHAR(100);
ALTER TABLE features
ADD COLUMN IF NOT EXISTS updated_by VARCHAR(100);
ALTER TABLE features
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;